spring.application.name=myOwnRealtorWebsite
# Database
spring.datasource.url=jdbc:mysql://localhost:3306/dreamhomes?useSSL=false&serverTimezone=UTC
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none

# Logging
logging.level.root=WARN
logging.level.com.example.myOwnRealtorWebsite=INFO

# Agent details
agent.name = YOUR_AGENT_NAME
agent.license-number = YOUR_LICENSE_NUMBER
agent.profile-picture-url = /images/agent.jpg
agent.home-page-url = /images/agentHomePage.JPG
agent.biography = YOUR_BIOGRAPHY
agent.speciality = YOUR_SPECIALITY
agent.years-of-experience = YOUR_YEARS
agent.total-sales-volume = YOUR_SALES_VOLUME

# Gmail SMTP settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_GMAIL
spring.mail.password=your-Gmail-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

upload.dir=src/main/resources/static/images/listings

# Password reset token expiry (minutes)
app.reset-token-expiry=30

# File upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true

spring.thymeleaf.enabled=true


cloudinary.cloud-name=YOUR_CLOUD_NAME
cloudinary.api-key=YOUR_API_KEY
cloudinary.api-secret=YOUR_API_SECRET

google.places.api-key=YOUR_GOOGLE_PLACES_API_KEY
google.places.place-id=YOUR_PLACE_ID